source 'https://rubygems.org'
gem 'rails', '4.2.0'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'sorcery'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'will_paginate', '~> 3.0.7'
#Generar XLSX
gem 'axlsx_rails', '~> 0.3.0'
#Generar PDF
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
#gem "pdfkit" 
group :development, :test do
	gem 'byebug'
	gem 'railroady'
	gem 'web-console', '~> 2.0'
	gem 'spring'
 	gem 'quiet_assets'
 	gem 'forgery'
	gem 'letter_opener'
	gem 'thin'
	gem 'better_errors'
	gem 'binding_of_caller'
	gem 'bullet'
	gem 'spring'
	gem 'annotate'
	gem 'rename'
	gem 'railroady'
end